### ISSUE TITLE
Multiple users with Clozes deleted

### ISSUE THREAD

**Issue by AnKingMed** [kelciour/edit_field_during_review#12]
I've had multiple users that have had their clozes deleted sending me an email over the last week and have seen a few posts on reddit. I don't know why so many all at once.

If you have time, perhaps adding something to prevent this from happening would be helpful

**Comment by kelciour** [comment]
Thank you very much for the issue! It was supposed to be fixed in 2020 after it happened to somebody else on Anki Forums and Damien suggested something similar, but it looks like I made a mistake and it wasn't fixed back there. I don't know how I didn't notice that the fix wasn't working after testing the changes, but it should be fixed now.

**Comment by AnKingMed** [comment]
Awesome! Thanks for doing that. Don't know why it's happened all of a sudden this week
